name: AWS S3 Bucket

on:
  push:
    branches: [ "feat/github-cd-demo" ]

# Necessary permissions for workflow
permissions:
  id-token: write
  contents: read

jobs:
  S3BucketIntegration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: unfor19/install-aws-cli-action@v1
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::576872909007:role/trackflix-live-oidc-mathis-Role-WZZyVRJVt9sJ
  
      - name: List S3 Bucket
        run: |
          echo "==> Listing all S3 buckets"
          aws s3 ls
