name: Deploy

# on:
#   push:
#     tags:
#       - 'demo-v*'
on:
  push:
    branches: [ "feat/github-cd-demo" ]

jobs:
  Deploy_backend:
    runs-on: ubuntu-latest
    env:
      STAGE: demo
      WAITING_SOURCE: s3://demo-videos-trackflix-live/waiting.mp4
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npx nx run api:deploy
  
  Deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npx nx run webui:upload
